Use the latest acr and update version to 5.2.0-git

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #!/bin/sh
-# This script was automatically generated by ACR v1.9.3
+# This script was automatically generated by ACR v1.9.8
 # @author: pancake <nopcode.org>
 # @url:    http://www.nopcode.org
 # @repo:   git clone https://github.com/radare/acr
@@ -40,6 +40,11 @@ shift
 done
 }
 
+QUIET=0
+be_quiet() {
+	QUIET=1
+}
+
 VPATH=`dirname ${0}`
 if [ "${VPATH}" = "." ]; then
 	WODIS=current
@@ -77,6 +82,7 @@ CROSSBUILD=0
 BUILD=`guess_os`
 HOST="${BUILD}"
 TARGET="${HOST}"
+ETCDIR="/etc"
 SYSCONFDIR=""
 
 create_environ() {
@@ -84,7 +90,7 @@ create_environ() {
 : ${SPREFIX:="${PREFIX}"}
 : ${BINDIR:="${SPREFIX}/bin"}
 : ${SBINDIR:="${PREFIX}/sbin"}
-: ${SYSCONFDIR:="${SPREFIX}/etc"}
+: ${ETCDIR:="${SPREFIX}/etc"}
 : ${LIBDIR:="${SPREFIX}/lib"}
 : ${LIBEXECDIR:="${SPREFIX}/libexec"}
 : ${INCLUDEDIR:="${SPREFIX}/include"}
@@ -104,12 +110,12 @@ done
 : ${INSTALL_PROGRAM_STRIP:=${INSTALL} -m 755 -s}
 : ${INSTALL_MAN:=${INSTALL} -m 444}
 : ${INSTALL_LIB:=${INSTALL} -m 755 -c}
- PKGNAME='radare2-rlang' ; VERSION='4.6.0-git' ; VERSION_MAJOR=4; VERSION_MINOR=6; VERSION_PATCH=0; VERSION_NUMBER=40600; CONTACT_MAIL="pancake@nopcode.org" ; CONTACT_NAME="pancake" ; CONTACT="pancake <pancake@nopcode.org>" ;
+ PKGNAME='radare2-rlang' ; VERSION='5.2.0-git' ; VERSION_MAJOR=5; VERSION_MINOR=2; VERSION_PATCH=0; VERSION_NUMBER=50200; CONTACT_MAIL="pancake@nopcode.org" ; CONTACT_NAME="pancake" ; CONTACT="pancake <pancake@nopcode.org>" ;
 }
 
 show_usage() {
 cat <<EOF2
-'configure' configures radare2-rlang-4.6.0-git to adapt to many kinds of systems.
+'configure' configures radare2-rlang-5.2.0-git to adapt to many kinds of systems.
 
 Usage: ./configure [OPTION]... [VAR=VALUE]...
 
@@ -121,6 +127,7 @@ Defaults for the options are specified in brackets.
 Configuration:
   -h, --help              display this help and exit
   -r, --report            show what libs/programs require to work
+  -q, --quiet             be quiet, less verbose (see ./configure -qV)
   -V, --version           display version information and exit
 
 Installation directories:
@@ -140,6 +147,7 @@ Fine tuning of the installation directories:
   --localstatedir=DIR    modifiable single-machine data [PREFIX/var]
   --mandir=DIR           man documentation [DATADIR/man]
   --sbindir=DIR          system admin executables [EPREFIX/sbin]
+  --etcdir=DIR           same as --sysconfdir (/etc)
   --sysconfdir=DIR       read-only single-machine data [PREFIX/etc]
   --sharedstatedir=DIR   modifiable architecture-independent data [PREFIX/com]
 
@@ -157,7 +165,6 @@ printf "
 Some influential environment variables:
   CC          C compiler command
   CFLAGS      C compiler flags
-  CPPFLAGS    C preprocessor flags
   LDFLAGS     linker flags, e.g. -L<lib dir> if you have libraries in a
               nonstandard directory <lib dir>
   CPPFLAGS    C/C++ preprocessor flags, e.g. -I<include dir> if you have
@@ -177,8 +184,22 @@ take_environ() {
 : ${PREFIX:=/usr/local/}
 }
 
+ochof() {
+	[ "$QUIET" = 1 ] && return
+	printf "$*"
+}
+
+ocho() {
+	[ "$QUIET" = 1 ] && return
+	echo "$*"
+}
+
 show_version() {
-echo "radare2-rlang-4.6.0-git configuration script done with acr v1.9.3.
+if [ "$QUIET" = 1 ]; then
+	echo "5.2.0-git"
+	exit 0
+fi
+echo "radare2-rlang-5.2.0-git configuration script done with acr v1.9.8.
 The 'Free Software Foundation' message is only for autodetection.
 Originally written by pancake <nopcode.org>."
 exit 0
@@ -198,11 +219,16 @@ fi
 case $flag in
 -h|--help|--hel|--h|--he|-help)
 	show_usage ; ;;
+-qV|-quiet-version|--quiet-version)
+	be_quiet
+	show_version ; ;;
+-q|-quiet|--quiet)
+	be_quiet ; ;;
 -V|-version|--version)
 	show_version ; ;;
 -r|--r|--report)
 echo "PKGNAME:   radare2-rlang"
-echo "VERSION:   4.6.0-git"
+echo "VERSION:   5.2.0-git"
 echo "LANGS:     c"
 echo "PKG-CONFIG:  r_core"
 echo "FLAGS:     --with-ostype=auto"
@@ -235,7 +261,11 @@ echo "FLAGS:     --with-ostype=auto"
 --datadir)
 	DATADIR="$value"; ;;
 --sysconfdir)
-	SYSCONFDIR="$value"; ;;
+	SYSCONFDIR="$value"
+	ETCDIR="$value"; ;;
+--etcdir)
+	SYSCONFDIR="$value"
+	ETCDIR="$value"; ;;
 --sharedstatedir)
 	SHAREDSTATEDIR="$value"; ;;
 --localstatedir)
@@ -269,23 +299,23 @@ parse_options "$1"
 shift
 done
 
-ENVWORDS="MANDIR INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR SYSCONFDIR DATADIR DOCDIR LIBEXECDIR SBINDIR BINDIR EPREFIX PREFIX SPREFIX TARGET HOST BUILD INSTALL INSTALL_LIB INSTALL_MAN INSTALL_PROGRAM INSTALL_PROGRAM_STRIP INSTALL_DIR INSTALL_SCRIPT INSTALL_DATA HOST_OS HOST_CPU BUILD_OS BUILD_CPU TARGET_OS TARGET_CPU VERSION VERSION_MAJOR VERSION_MINOR VERSION_PATCH VERSION_NUMBER PKGNAME VPATH CONTACT CONTACT_NAME CONTACT_MAIL CC CFLAGS CPPFLAGS LDFLAGS HAVE_LANG_C R2_CFLAGS R2_LDFLAGS HAVE_PKGCFG_R_CORE USEROSTYPE"
+ENVWORDS="MANDIR INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR ETCDIR SYSCONFDIR DATADIR DOCDIR LIBEXECDIR SBINDIR BINDIR EPREFIX PREFIX SPREFIX TARGET HOST BUILD INSTALL INSTALL_LIB INSTALL_MAN INSTALL_PROGRAM INSTALL_PROGRAM_STRIP INSTALL_DIR INSTALL_SCRIPT INSTALL_DATA HOST_OS HOST_CPU BUILD_OS BUILD_CPU TARGET_OS TARGET_CPU VERSION VERSION_MAJOR VERSION_MINOR VERSION_PATCH VERSION_NUMBER PKGNAME VPATH CONTACT CONTACT_NAME CONTACT_MAIL CC CFLAGS CPPFLAGS LDFLAGS HAVE_LANG_C PKGCONFIG R2_CFLAGS R2_LDFLAGS HAVE_PKGCFG_R_CORE USEROSTYPE"
 
 create_environ
 
-echo "checking build system type... ${BUILD}"
-echo "checking host system type... ${HOST}"
-echo "checking target system type... ${TARGET}"
+ocho "checking build system type... ${BUILD}"
+ocho "checking host system type... ${HOST}"
+ocho "checking target system type... ${TARGET}"
 [ "${CROSSBUILD}" = 1 ] && echo "using crosscompilation mode."
 
 #split_host BUILD HOST TARGET
 [ -n "${prefix}" ] && PREFIX="${prefix}"
-echo "checking for working directories... ${WODIS}"
-echo "using prefix '${PREFIX}'"
+ocho "checking for working directories... ${WODIS}"
+ocho "using prefix '${PREFIX}'"
 ACR_RMFILES=" test.c a.out a.exe"
 
 COMPILER=CC
-printf "checking for c compiler... "
+ochof "checking for c compiler... "
 HAVE_LANG_C=1
 if [ "${CROSSBUILD}" = 1 ]; then
  (command -v ${HOST}-${CC} >/dev/null 2>&1)
@@ -298,8 +328,35 @@ if [ $? = 0 ]; then echo ${CC}; else
 do_remove
 echo "ERROR: ${CC} cannot create executables" >&2 ;
 exit 1 ; fi
-[ -z "${PKGCONFIG}" ] && PKGCONFIG=pkg-config
-type ${PKGCONFIG} > /dev/null 2>&1 || echo "ERROR: Cannot find PKGCONFIG ${PKGCONFIG}"
+ochof "checking for pkg-config... "
+if [ -n "$PKGCONFIG" ]; then
+	if [ -x "$PKGCONFIG" ]; then
+		_HAVE_PKGCONFIG="${PKGCONFIG}"
+	else
+		ocho "PKGCONFIG env is not executable"
+		PKGCONFIG=""
+	fi
+else
+	IFS=:
+	for A in ${PATH} ; do
+		if [ -x "${A}/pkg-config" ]; then
+			PKGCONFIG="${A}/pkg-config"
+		elif [ -x "${A}/pkgconf" ]; then
+			PKGCONFIG="${A}/pkgconf"
+		else
+			continue
+		fi
+		break
+	done
+	unset IFS
+fi
+if [ -n "${PKGCONFIG}" ]; then
+	ocho ${PKGCONFIG}
+else
+	echo "Cannot find pkg-config or pkgconf in PATH" >&2
+	exit 1 ocho no; fi
+if [ -z "${PKGCONFIG}" ]; then pkg-config --version >/dev/null 2>&1 ; if [ 0 = 0 ]; then PKGCONFIG=pkg-config ; else PKGCONFIG=pkgconf ; fi; fi
+type ${PKGCONFIG} > /dev/null 2>&1 || echo "ERROR: Cannot find valid PKGCONFIG, pkg-config or pkgconf in PATH"
 echo 'Using PKGCONFIG: '${PKGCONFIG}
 printf 'checking pkg-config flags for r_core... '
 tmp=`${PKGCONFIG} --cflags r_core 2>/dev/null`
@@ -337,8 +394,8 @@ if [ -f "${VPATH}/${A}.acr" ]; then
    exit 1
   fi
  fi
- echo "creating ${SD_TARGET}"
-mkdir -p $(echo ${A} | sed -e "s,/`basename ${A}`$,,g")
+ ocho "creating ${SD_TARGET}"
+[ "${VPATH}" != '.' ] &&  mkdir -p $(echo ${A} | sed -e "s,/`basename ${A}`$,,g")
  cat ${VPATH}/${SD_TARGET}.acr | \
 eval sed -e "s,@VPATH@,${VPATH}/${A},g" ${SEDFLAGS} > ${SD_TARGET}.tmp
 
@@ -357,10 +414,12 @@ done
 done
 
 do_remove
+if [ "$QUIET" = 0 ]; then
 echo
 echo "Final report:"
-for A in  PREFIX ; do # REPORT
+for A in  PREFIX ; do
 eval VAL="\$${A}"
 [ -z "${VAL}" ] && VAL="(null)"
 echo " - ${A} = ${VAL}"
 done
+fi
